# YOLOv11 Dataset Configuration - LIBRAS Alphabet Detection
# Configuração para detecção de alfabeto em Linguagem Brasileira de Sinais

# Caminhos absolutos para os datasets
train: C:/Users/Nicolas/Desktop/computer-vision/dataset/train/images
val: C:/Users/Nicolas/Desktop/computer-vision/dataset/valid/images
test: C:/Users/Nicolas/Desktop/computer-vision/dataset/test/images

# Número de classes
nc: 22

# Nomes das classes (letras em LIBRAS)
names:
  [
    "A",
    "B",
    "C",
    "D1",
    "D2",
    "E",
    "F",
    "G",
    "I",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
  ]
